name: Build and push docker image
run-name: ${{ github.actor }} is building
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pwd && ls -la ..
      - run: cd service-skeleton-challenge-main/go-service-skeleton && make docker-build
      - run: cd service-skeleton-challenge-main/go-service-skeleton && make docker-push
